// ============================================================================
// src/modules/reports/reports.pdf.js  —  PDFKit ISRO one-page-template renderer
// ----------------------------------------------------------------------------
// PHASE 10 — Reports & Analytics
//
// PURPOSE
//   Streams a PDF document that replicates the attached one-page template:
//     • ISRO + SAC seal block (left/right) + "SPACE APPLICATIONS CENTRE /
//       TIMCD" title block, plus the report-specific title
//     • Header strip: Report ID · Generated On · Date Range · Generated By
//     • Section 1 — Report Scope & Data Source
//     • Section 2 — Summary Snapshot (the KPI tiles row)
//     • Section 3 — Detailed table (auto-paginates with repeating header
//                                   when data exceeds one page)
//     • Section 4 — Business Rules & Validation Notes + Approval Rule
//     • Footer on every page: Page N of M
//
// DESIGN GUARANTEES
//   • Streams to res (no temp files, no DB writes) — Phase-10 §1.F.
//   • No external network calls (no remote logos). The ISRO/SAC seal
//     blocks are rendered as styled cells with INDIA + ISRO + SAC text;
//     if a real SVG/PNG is later dropped into src/assets/, this file
//     can pick it up with a single line change.
//   • Auto-paginates safely on >1k rows: PDFKit writes rows on demand
//     and we call doc.addPage() before overflowing the bottom margin.
//   • Page-number stamping happens in a SECOND pass over doc.bufferedPageRange()
//     so we know the final total before stamping "Page X of Y".
//
// MODULES TOUCHED
//   reports.pdf.js   ← this file
//   reports.controller.js   ← pipes the PDF stream into the HTTP response
//   reports.service.js      ← provides the payload shape we render here
// ============================================================================

'use strict';

const PDFDocument = require('pdfkit');
const {
  drawHeader: isroDrawHeader,
  PAGE_MARGIN_X,
  PAGE_MARGIN_BOTTOM,
  FOOTER_HEIGHT,
  COLORS,
} = require('../pdf/templates/_isroHeader');

const PAGE_MARGIN_TOP = 36;

const COLOR_TITLE    = COLORS.title;
const COLOR_BORDER   = COLORS.border;
const COLOR_HEADER   = COLORS.headerBg;
const COLOR_SUBTLE   = COLORS.subtle;
const COLOR_INK_SOFT = COLORS.inkSoft;

// ── Helpers ────────────────────────────────────────────────────────────

function fmtDate(d) {
  if (!d) return '—';
  const dt = (d instanceof Date) ? d : new Date(d);
  if (Number.isNaN(dt.getTime())) return String(d);
  // dd-mm-yyyy to match the filter inputs in the attached UI.
  const dd = String(dt.getUTCDate()).padStart(2, '0');
  const mm = String(dt.getUTCMonth() + 1).padStart(2, '0');
  const yy = dt.getUTCFullYear();
  return `${dd}-${mm}-${yy}`;
}

function fmtDateTime(d) {
  if (!d) return '—';
  const dt = (d instanceof Date) ? d : new Date(d);
  if (Number.isNaN(dt.getTime())) return String(d);
  const date = fmtDate(dt);
  const hh = String(dt.getUTCHours()).padStart(2, '0');
  const mi = String(dt.getUTCMinutes()).padStart(2, '0');
  return `${date} ${hh}:${mi} UTC`;
}

function rangeLabel(filters) {
  if (filters.date_from && filters.date_to) return `${filters.date_from} → ${filters.date_to}`;
  if (filters.date_from) return `From ${filters.date_from}`;
  if (filters.date_to)   return `Until ${filters.date_to}`;
  return 'All time';
}

// ── HEADER (ISRO/SAC seal + title block) ───────────────────────────────
function drawHeader(doc, payload, opts) {
  const pageWidth  = doc.page.width;
  const leftX  = PAGE_MARGIN_X;
  const rightX = pageWidth - PAGE_MARGIN_X;

  // Draw shared header using imported helper
  isroDrawHeader(doc, {
    title: payload.meta.report_title.toUpperCase(),
    subtitle: 'CMCMIS · Space Applications Centre TIMCD',
    compact: true,
  });

  // ── META STRIP (Report ID · Generated On · Range · Generated By) ──
  const meta = payload.meta;
  const stripY = doc.y;
  const stripH = 18;
  doc.lineWidth(0.4).strokeColor(COLOR_BORDER);
  doc.roundedRect(leftX, stripY, rightX - leftX, stripH, 3).fillAndStroke('#F8FAFC', COLOR_BORDER);
  doc.roundedRect(leftX, stripY, 3, stripH, 1.5).fill(COLORS.accent);

  doc.fillColor(COLORS.accent).font('Helvetica-Bold').fontSize(7);
  const colW = (rightX - leftX) / 4;
  doc.text('Report ID',       leftX + 9,                stripY + 3, { width: colW - 12, align: 'left', lineBreak: false });
  doc.text('Generated On',    leftX + 9 + colW,         stripY + 3, { width: colW - 12, align: 'left', lineBreak: false });
  doc.text('Range',           leftX + 9 + colW * 2,     stripY + 3, { width: colW - 12, align: 'left', lineBreak: false });
  doc.text('Generated By',    leftX + 9 + colW * 3,     stripY + 3, { width: colW - 12, align: 'left', lineBreak: false });
  
  doc.font('Helvetica').fontSize(8).fillColor(COLOR_TITLE);
  doc.text(meta.report_id,                            leftX + 9,            stripY + 10, { width: colW - 12, align: 'left', lineBreak: false });
  doc.text(fmtDateTime(meta.generated_on),            leftX + 9 + colW,     stripY + 10, { width: colW - 12, align: 'left', lineBreak: false });
  doc.text(rangeLabel(meta.filters),                  leftX + 9 + colW * 2, stripY + 10, { width: colW - 12, align: 'left', lineBreak: false });
  doc.text(`${meta.generated_by.name} (${meta.generated_by.role || '—'})`,
           leftX + 9 + colW * 3, stripY + 10, { width: colW - 12, align: 'left', lineBreak: false });
  doc.y = stripY + stripH + 6;

  // Title-bar of section 1.
  drawSectionBar(doc, '1. REPORT SCOPE & DATA SOURCE', opts.sourceLabel);
}

function drawSectionBar(doc, title, rightLabel) {
  const leftX = PAGE_MARGIN_X;
  const rightX = doc.page.width - PAGE_MARGIN_X;
  const y = doc.y;
  doc.font('Helvetica-Bold').fontSize(8.5).fillColor(COLOR_TITLE);
  doc.text(title, leftX, y);
  if (rightLabel) {
    doc.font('Helvetica').fontSize(7.5).fillColor(COLOR_INK_SOFT);
    doc.text(rightLabel, leftX, y, { align: 'right', width: rightX - leftX });
  }
  doc.moveTo(leftX, y + 11).lineTo(rightX, y + 11).strokeColor(COLOR_BORDER).lineWidth(0.4).stroke();
  doc.y = y + 14;
  doc.fillColor(COLOR_TITLE);
}

// Section 1 — three-column "source" tiles (e.g. PRIMARY · JOIN · LOGIC).
function drawScopeBlock(doc, items) {
  const leftX = PAGE_MARGIN_X;
  const rightX = doc.page.width - PAGE_MARGIN_X;
  const totalW = rightX - leftX;
  const gap = 6;
  const w = (totalW - (items.length - 1) * gap) / items.length;
  const y = doc.y;
  const h = 28;
  
  items.forEach((it, i) => {
    const x = leftX + i * (w + gap);
    
    // Draw premium rounded card with a subtle border and background fill
    doc.lineWidth(0.4).strokeColor(COLOR_BORDER);
    doc.roundedRect(x, y, w, h, 3).fillAndStroke('#F8FAFC', COLOR_BORDER);
    
    // Draw left accent bar in accent blue
    doc.roundedRect(x, y, 3, h, 1.5).fill(COLORS.accent);
    
    doc.font('Helvetica-Bold').fontSize(7).fillColor(COLORS.accent);
    doc.text(it.label.toUpperCase(), x + 9, y + 4, { width: w - 14, lineBreak: false });
    
    doc.font('Courier-Bold').fontSize(8.5).fillColor(COLORS.title);
    doc.text(it.value, x + 9, y + 14, { width: w - 14, lineBreak: false });
  });
  doc.y = y + h + 6;
}

// Section 2 — KPI summary snapshot tiles (one per metric).
function drawSummaryBlock(doc, tiles) {
  drawSectionBar(doc, '2. SUMMARY SNAPSHOT', 'AUTO-CALCULATED FROM LIVE CMCMIS DATA');
  const leftX  = PAGE_MARGIN_X;
  const rightX = doc.page.width - PAGE_MARGIN_X;
  const totalW = rightX - leftX;
  const gap = 6;
  const w = (totalW - (tiles.length - 1) * gap) / tiles.length;
  const y = doc.y;
  const h = 36;
  
  const tileColors = ['#1f3a8a', '#D97706', '#4F46E5', '#16A34A'];

  tiles.forEach((t, i) => {
    const x = leftX + i * (w + gap);
    const col = tileColors[i % tileColors.length];

    // Draw premium rounded card with a subtle border and background fill
    doc.lineWidth(0.4).strokeColor(COLOR_BORDER);
    doc.roundedRect(x, y, w, h, 3).fillAndStroke('#F8FAFC', COLOR_BORDER);
    
    // Draw left accent bar in status color
    doc.roundedRect(x, y, 3, h, 1.5).fill(col);

    doc.font('Helvetica-Bold').fontSize(6.5).fillColor(col);
    doc.text(t.label.toUpperCase(), x + 9, y + 4, { width: w - 14, lineBreak: false });
    
    doc.font('Helvetica-Bold').fontSize(13).fillColor(COLORS.title);
    doc.text(String(t.value), x + 9, y + 12, { width: w - 14, lineBreak: false });
    
    if (t.subtitle) {
      doc.font('Helvetica').fontSize(6.5).fillColor(COLORS.inkSoft);
      doc.text(t.subtitle, x + 9, y + 24, { width: w - 14, lineBreak: false });
    }
  });
  doc.y = y + h + 8;
}

// Section 3 — paginated detailed table.
//
// `columns` is an array of { key, label, width, align? }. width values
// should sum to roughly (pageWidth - 2*MARGIN). We re-draw the header
// row at the top of every new page.
function drawTable(doc, sectionTitle, rightHint, columns, rows, reportTitle) {
  drawSectionBar(doc, sectionTitle, rightHint);

  const leftX  = PAGE_MARGIN_X;
  const rightX = doc.page.width - PAGE_MARGIN_X;
  const tableW = rightX - leftX;

  // Auto-fit columns so widths sum to tableW exactly.
  const totalRaw = columns.reduce((a, c) => a + c.width, 0);
  const widths = columns.map((c) => (c.width / totalRaw) * tableW);

  const ROW_PAD = 2.5;
  const HEADER_H = 16;

  function drawHeaderRow() {
    const hy = doc.y;
    doc.rect(leftX, hy, tableW, HEADER_H).fillAndStroke(COLORS.accent, COLORS.border);
    doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(7.5);
    let cx = leftX;
    columns.forEach((c, i) => {
      doc.text(c.label, cx + ROW_PAD, hy + 4, {
        width: widths[i] - 2 * ROW_PAD,
        align: c.align || 'left',
        lineBreak: false,
      });
      cx += widths[i];
    });
    doc.y = hy + HEADER_H;
  }

  drawHeaderRow();

  doc.font('Helvetica').fontSize(7.5).fillColor(COLOR_TITLE);
  const lineHeight = 9.5;

  if (!rows || rows.length === 0) {
    const y = doc.y;
    doc.rect(leftX, y, tableW, 20).strokeColor(COLOR_BORDER).lineWidth(0.5).stroke();
    doc.fillColor(COLOR_INK_SOFT).text(
      'No rows match the current filter.',
      leftX, y + 6,
      { width: tableW, align: 'center' }
    );
    doc.y = y + 20;
    return;
  }

  let rowIdx = 0;
  rows.forEach((row) => {
    // Estimate row height = max wrapped height of any cell.
    let maxLines = 1;
    columns.forEach((c, i) => {
      const v = String(row[c.key] ?? '');
      const w = widths[i] - 2 * ROW_PAD;
      // Cheap line estimate based on average char width (Helvetica 7.5pt ~4.2pt/char).
      const chars = v.length;
      const charsPerLine = Math.max(8, Math.floor(w / 4.2));
      const lines = Math.max(1, Math.ceil(chars / charsPerLine));
      if (lines > maxLines) maxLines = Math.min(lines, 4);   // cap at 4 lines/cell
    });
    const rowH = Math.max(13, ROW_PAD * 2 + maxLines * lineHeight);

    // Page-break BEFORE drawing the row.
    if (doc.y + rowH > doc.page.height - PAGE_MARGIN_BOTTOM - FOOTER_HEIGHT) {
      doc.addPage();
      isroDrawHeader(doc, {
        title: reportTitle.toUpperCase(),
        subtitle: 'CMCMIS · Space Applications Centre TIMCD',
        compact: true,
      });
      doc.y += 10;
      drawHeaderRow();
    }

    const ry = doc.y;
    const isOdd = rowIdx % 2 !== 0;
    const rowBgColor = isOdd ? '#EDF1F7' : '#FFFFFF';
    rowIdx++;

    doc.lineWidth(0.25);
    doc.rect(leftX, ry, tableW, rowH).fillAndStroke(rowBgColor, COLORS.border);

    let cx = leftX;
    columns.forEach((c, i) => {
      const raw = row[c.key];
      const v = c.format ? c.format(raw, row) : (raw === null || raw === undefined ? '—' : String(raw));
      doc.fillColor(COLOR_TITLE).font('Helvetica').fontSize(7.5);
      doc.text(v, cx + ROW_PAD, ry + ROW_PAD, {
        width: widths[i] - 2 * ROW_PAD,
        align: c.align || 'left',
        lineBreak: true,
        ellipsis: true,
        height: rowH - 2 * ROW_PAD,
      });
      cx += widths[i];
    });
    doc.y = ry + rowH;
  });

  // Trailing footnote (right-aligned italic).
  const fy = doc.y + 4;
  doc.font('Helvetica-Oblique').fontSize(7).fillColor(COLOR_INK_SOFT);
  doc.text('Rows are dynamically populated from backend query / export service.',
    leftX, fy, { width: tableW, align: 'right' });
  doc.y = fy + 10;
}

// Section 4 — Business Rules & Validation Notes + Approval Rule.
function drawBusinessNotes(doc, bullets, approvalRule, legend) {
  if (doc.y > doc.page.height - PAGE_MARGIN_BOTTOM - 100) doc.addPage();
  drawSectionBar(doc, '4. BUSINESS RULES & VALIDATION NOTES', 'REPORT-MODULE ACCEPTANCE CRITERIA');

  const leftX  = PAGE_MARGIN_X;
  const rightX = doc.page.width - PAGE_MARGIN_X;
  const gap = 6;
  const colW = (rightX - leftX - 2 * gap) / 3;
  const colY = doc.y;
  const colH = 92;

  // Column 1 — Derived logic bullets
  doc.lineWidth(0.4).strokeColor(COLOR_BORDER);
  doc.roundedRect(leftX, colY, colW, colH, 3).fillAndStroke('#F8FAFC', COLOR_BORDER);
  doc.roundedRect(leftX, colY, 3, colH, 1.5).fill('#1f3a8a');
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#1f3a8a')
     .text('DERIVED LOGIC', leftX + 10, colY + 6, { width: colW - 16, lineBreak: false });
  doc.font('Helvetica').fontSize(7.5).fillColor(COLOR_TITLE);
  let ly = colY + 18;
  bullets.forEach((b) => {
    doc.text('• ' + b, leftX + 10, ly, { width: colW - 18 });
    ly = doc.y + 2;
  });

  // Column 2 — Status legend
  const c2x = leftX + colW + gap;
  doc.roundedRect(c2x, colY, colW, colH, 3).fillAndStroke('#F8FAFC', COLOR_BORDER);
  doc.roundedRect(c2x, colY, 3, colH, 1.5).fill('#D97706');
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#D97706')
     .text('STATUS LEGEND', c2x + 10, colY + 6, { width: colW - 16, lineBreak: false });
  doc.font('Courier-Bold').fontSize(7.5).fillColor(COLOR_TITLE);
  doc.text(legend.join('  ·  '), c2x + 10, colY + 20, { width: colW - 18 });

  // Column 3 — Approval rule
  const c3x = c2x + colW + gap;
  doc.roundedRect(c3x, colY, colW, colH, 3).fillAndStroke('#F8FAFC', COLOR_BORDER);
  doc.roundedRect(c3x, colY, 3, colH, 1.5).fill('#16A34A');
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#16A34A')
     .text('APPROVAL RULE', c3x + 10, colY + 6, { width: colW - 16, lineBreak: false });
  doc.font('Helvetica').fontSize(7.5).fillColor(COLOR_TITLE);
  doc.text(approvalRule, c3x + 10, colY + 18, { width: colW - 18 });

  doc.y = colY + colH + 4;
}

// Footer (Page X of Y, generated stamp). Run as a second pass after we
// know the total page count.
function stampFooters(doc) {
  const range = doc.bufferedPageRange();   // { start, count }
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);

    // Temporarily disable margins.bottom to prevent PDFKit auto-pagination page leak
    const oldBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;

    const y = doc.page.height - PAGE_MARGIN_BOTTOM + 6;
    const leftX = PAGE_MARGIN_X;
    const rightX = doc.page.width - PAGE_MARGIN_X;
    doc.font('Helvetica').fontSize(8).fillColor(COLORS.inkSoft);

    const leftStr = `Generated by CMCMIS · ${new Date().toISOString().slice(0, 19).replace('T', ' ')} UTC`;

    doc.text(
      leftStr,
      leftX, y, { width: rightX - leftX, align: 'left', lineBreak: false }
    );
    doc.text(
      `Page ${i - range.start + 1} of ${range.count}`,
      leftX, y, { width: rightX - leftX, align: 'right', lineBreak: false }
    );

    // Restore original bottom margin
    doc.page.margins.bottom = oldBottom;
  }
}

// Common legend constant used across reports.
const STATUS_LEGEND = ['VALID', 'DUE_SOON', 'OVERDUE', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED_CLOSED'];

// ── Per-report renderers ───────────────────────────────────────────────
// Each function takes a `payload` (the service output) and a writable
// `stream` (typically the Express `res` object). The function:
//   1. Creates a PDFDocument piped to the stream.
//   2. Draws header → section 1 → section 2 → section 3 (table) → section 4.
//   3. Stamps footers in a second pass.
//   4. Calls doc.end() to flush.

function renderCalibrationDuePdf(payload, stream) {
  const doc = new PDFDocument({
    size: 'A4',
    layout: 'landscape',
    margin: PAGE_MARGIN_X,
    bufferPages: true,
    autoFirstPage: true,
  });
  doc.pipe(stream);

  drawHeader(doc, payload, { sourceLabel: 'SOURCE: CMMS_EQIP_MST' });

  drawScopeBlock(doc, [
    { label: 'Primary Source', value: 'cmms_eqip_mst' },
    { label: 'Division Join',  value: 'cmms_section_mst' },
    { label: 'Status Logic',   value: 'VALID / DUE_SOON / OVERDUE' },
  ]);

  const s = payload.summary;
  drawSummaryBlock(doc, [
    { label: 'Total Equipment', value: s.total,    subtitle: 'COUNT(EQM_ID)' },
    { label: 'Due Soon',        value: s.due_soon, subtitle: `Within ${payload.meta.filters.due_soon_days ?? 30} days` },
    { label: 'Overdue',         value: s.overdue,  subtitle: 'today > due date' },
    { label: 'Valid',           value: s.valid,    subtitle: 'beyond alert window' },
  ]);

  drawTable(doc,
    '3. DETAILED CALIBRATION DUE REPORT DATA',
    'RESPECTIVELY MAPPED REPORT COLUMNS',
    [
      { key: 'equipment_id',      label: 'Equipment ID',      width: 75 },
      { key: 'equipment_name',    label: 'Equipment Name',    width: 160 },
      { key: 'serial_number',     label: 'Serial Number',     width: 90 },
      { key: 'division',          label: 'Division',          width: 80 },
      { key: 'last_cal_date',     label: 'Last Calibration',  width: 80, format: fmtDate },
      { key: 'next_cal_due_date', label: 'Next Due',          width: 80, format: fmtDate },
      { key: 'calibration_status',label: 'Cal Status',        width: 70 },
      { key: 'equipment_status',  label: 'Equipment Status',  width: 95 },
    ],
    payload.rows,
    payload.meta.report_title,
  );

  drawBusinessNotes(doc, [
    'Calibration status is derived from next calibration due date.',
    'Due Soon threshold configurable by admin (default 30 days).',
    'Division name is resolved through cmms_section_mst.',
  ], 'Acceptable when every active equipment has due date, division, status and traceable equipment ID.', STATUS_LEGEND);

  stampFooters(doc);
  doc.end();
}

function renderPendingJobsPdf(payload, stream) {
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: PAGE_MARGIN_X, bufferPages: true });
  doc.pipe(stream);
  drawHeader(doc, payload, { sourceLabel: 'SOURCE: CMMS_JOBREQUEST_MST' });

  drawScopeBlock(doc, [
    { label: 'Primary Source', value: 'cmms_jobrequest_mst' },
    { label: 'Equipment Join', value: 'cmms_eqip_mst' },
    { label: 'Division Join',  value: 'cmms_section_mst' },
  ]);

  const s = payload.summary;
  drawSummaryBlock(doc, [
    { label: 'Total Pending', value: s.total_pending, subtitle: 'JR_MVP_STATUS pending/open' },
    { label: 'New Requests',  value: s.new_requests,  subtitle: 'in selected range' },
    { label: 'Assigned',      value: s.assigned,      subtitle: 'JR_ASSIGNED_ENGINEER present' },
    { label: 'Unassigned',    value: s.unassigned,    subtitle: 'engineer not assigned' },
  ]);

  drawTable(doc,
    '3. DETAILED PENDING JOBS REPORT DATA',
    'RESPECTIVELY MAPPED REPORT COLUMNS',
    [
      { key: 'request_code',           label: 'Job Request ID',     width: 85 },
      { key: 'equipment_name',         label: 'Equipment Name',     width: 130 },
      { key: 'job_type',               label: 'Job Type',           width: 75 },
      { key: 'status',                 label: 'Status',             width: 75 },
      { key: 'submitted_by_name',      label: 'Submitted By',       width: 110 },
      { key: 'submitted_date',         label: 'Submitted On',       width: 75, format: fmtDate },
      { key: 'division',               label: 'Division',           width: 70 },
      { key: 'assigned_engineer_name', label: 'Assigned Engineer',  width: 110,
        format: (v) => v && v.trim() ? v : 'Unassigned' },
    ],
    payload.rows,
    payload.meta.report_title,
  );

  drawBusinessNotes(doc, [
    'Only jobs NOT completed/closed appear in pending report.',
    'Equipment name resolved from cmms_eqip_mst via composite FK.',
    'Assigned engineer rendered as "Unassigned" when blank.',
  ], 'Acceptable when each request includes ID, status, submitter, date, division and engineer ownership.', STATUS_LEGEND);

  stampFooters(doc);
  doc.end();
}

function renderEquipmentUtilizationPdf(payload, stream) {
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: PAGE_MARGIN_X, bufferPages: true });
  doc.pipe(stream);
  drawHeader(doc, payload, { sourceLabel: 'SOURCE: CMMS_EQIP_MST + CMMS_JOBCARD_MST' });

  drawScopeBlock(doc, [
    { label: 'Equipment Source', value: 'cmms_eqip_mst' },
    { label: 'Job Card Source',  value: 'cmms_jobcard_mst' },
    { label: 'Aggregation',      value: 'COUNT from cmms_jobcard_mst' },
  ]);

  const s = payload.summary;
  drawSummaryBlock(doc, [
    { label: 'Total Equipment',   value: s.total_equipment,  subtitle: 'COUNT(EQM_ID)' },
    { label: 'Used Equipment',    value: s.used_equipment,   subtitle: 'with job cards in window' },
    { label: 'Total Job Cards',   value: s.total_job_cards,  subtitle: 'COUNT(JC records)' },
    { label: 'Inactive / Low Use',value: s.inactive_low_use, subtitle: '0 JCs in window' },
  ]);

  drawTable(doc,
    '3. DETAILED EQUIPMENT UTILIZATION REPORT DATA',
    'RESPECTIVELY MAPPED REPORT COLUMNS',
    [
      { key: 'equipment_id',     label: 'Equipment ID',  width: 80 },
      { key: 'equipment_name',   label: 'Equipment Name',width: 180 },
      { key: 'serial_number',    label: 'Serial Number', width: 90 },
      { key: 'equipment_type',   label: 'Equipment Type',width: 110 },
      { key: 'total_job_cards',  label: 'Total Job Cards',width: 80, align: 'right' },
      { key: 'division',         label: 'Division',       width: 80 },
      { key: 'equipment_status', label: 'Status',         width: 110 },
    ],
    payload.rows,
    payload.meta.report_title,
  );

  drawBusinessNotes(doc, [
    'Utilization is calculated by counting job cards per equipment.',
    'Date filter limits job card count to selected operational period.',
    'Equipment status comes from cmms_eqip_mst.EQM_MVP_STATUS.',
  ], 'Acceptable when identity, type, division, status and total job-card count are visible in one line.', STATUS_LEGEND);

  stampFooters(doc);
  doc.end();
}

function renderEngineerSummaryPdf(payload, stream) {
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: PAGE_MARGIN_X, bufferPages: true });
  doc.pipe(stream);
  drawHeader(doc, payload, { sourceLabel: 'SOURCE: CMMS_JOBCARD_MST + CMMS_EMP_MST' });

  drawScopeBlock(doc, [
    { label: 'Primary Source', value: 'cmms_jobcard_mst' },
    { label: 'Employee Join',  value: 'cmms_emp_mst' },
    { label: 'Date Filter',    value: 'JM_JCRecdDate' },
  ]);

  const s = payload.summary;
  drawSummaryBlock(doc, [
    { label: 'Engineers',    value: s.engineers,    subtitle: 'distinct assigned engineers' },
    { label: 'Assigned JCs', value: s.assigned_jcs, subtitle: 'total assigned' },
    { label: 'Completed',    value: s.completed,    subtitle: 'JM_MVP_STATUS = COMPLETED' },
    { label: 'In Progress',  value: s.in_progress,  subtitle: 'JM_MVP_STATUS = IN_PROGRESS' },
  ]);

  drawTable(doc,
    '3. DETAILED ENGINEER SUMMARY REPORT DATA',
    'RESPECTIVELY MAPPED REPORT COLUMNS',
    [
      { key: 'engineer_employee_id', label: 'Engineer ID',     width: 80 },
      { key: 'engineer_name',        label: 'Engineer Name',   width: 180 },
      { key: 'total_assigned',       label: 'Total Assigned',  width: 90, align: 'right' },
      { key: 'completed',            label: 'Completed',       width: 80, align: 'right' },
      { key: 'in_progress',          label: 'In Progress',     width: 80, align: 'right' },
      { key: 'verified_closed',      label: 'Verified/Closed', width: 90, align: 'right' },
      { key: 'date_range_from',      label: 'First JC',        width: 80, format: fmtDate },
      { key: 'date_range_to',        label: 'Last JC',         width: 80, format: fmtDate },
    ],
    payload.rows,
    payload.meta.report_title,
  );

  drawBusinessNotes(doc, [
    'Engineer name resolved from cmms_emp_mst by employee_id.',
    'Status counts grouped by JM_ASSIGNED_ENGINEER within range.',
    'Verified/Closed includes JCs reaching final verified stage.',
  ], 'Acceptable when workload, completed, in-progress and verified/closed counts are grouped per engineer.', STATUS_LEGEND);

  stampFooters(doc);
  doc.end();
}

function renderJobCardSummaryPdf(payload, stream) {
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: PAGE_MARGIN_X, bufferPages: true });
  doc.pipe(stream);
  drawHeader(doc, payload, { sourceLabel: 'SOURCE: CMMS_JOBCARD_MST' });

  drawScopeBlock(doc, [
    { label: 'Primary Source', value: 'cmms_jobcard_mst' },
    { label: 'Equipment Join', value: 'cmms_eqip_mst' },
    { label: 'Employee Join',  value: 'cmms_emp_mst' },
  ]);

  const s = payload.summary;
  drawSummaryBlock(doc, [
    { label: 'Total JCs',      value: s.total,           subtitle: 'all in range' },
    { label: 'Open/Assigned',  value: s.open_assigned,   subtitle: 'awaiting start' },
    { label: 'In Progress',    value: s.in_progress,     subtitle: 'currently being worked' },
    { label: 'Verified/Closed',value: s.verified_closed, subtitle: 'final state' },
  ]);

  drawTable(doc,
    '3. DETAILED JOB CARD SUMMARY REPORT DATA',
    'RESPECTIVELY MAPPED REPORT COLUMNS',
    [
      { key: 'job_card_no',             label: 'Job Card No',      width: 85 },
      { key: 'equipment_name',          label: 'Equipment Name',   width: 150 },
      { key: 'job_type',                label: 'Job Type',         width: 80 },
      { key: 'status',                  label: 'Status',           width: 90 },
      { key: 'assigned_engineer_name',  label: 'Engineer',         width: 110 },
      { key: 'received_date',           label: 'Received',         width: 70, format: fmtDate },
      { key: 'completed_date',          label: 'Completed',        width: 70, format: fmtDate },
      { key: 'verified_date',           label: 'Verified',         width: 70, format: fmtDate },
      { key: 'division',                label: 'Division',         width: 60 },
    ],
    payload.rows,
    payload.meta.report_title,
  );

  drawBusinessNotes(doc, [
    'Job type comes from parent JR (JR_JOB_TYPE) when linked.',
    'Engineer name resolved from cmms_emp_mst by employee_id.',
    'Date filter applies to JM_JCRecdDate.',
  ], 'Acceptable when each row shows Job Card No, status, engineer, key timestamps and division.', STATUS_LEGEND);

  stampFooters(doc);
  doc.end();
}

function renderJobRequestSummaryPdf(payload, stream) {
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: PAGE_MARGIN_X, bufferPages: true });
  doc.pipe(stream);
  drawHeader(doc, payload, { sourceLabel: 'SOURCE: CMMS_JOBREQUEST_MST' });

  drawScopeBlock(doc, [
    { label: 'Primary Source', value: 'cmms_jobrequest_mst' },
    { label: 'Equipment Join', value: 'cmms_eqip_mst' },
    { label: 'Division Join',  value: 'cmms_section_mst' },
  ]);

  const s = payload.summary;
  drawSummaryBlock(doc, [
    { label: 'Total Requests',  value: s.total,           subtitle: 'all states' },
    { label: 'Submitted',       value: s.submitted,       subtitle: 'awaiting approval' },
    { label: 'Assigned',        value: s.assigned,        subtitle: 'engineer assigned' },
    { label: 'Verified/Closed', value: s.verified_closed, subtitle: 'final state' },
  ]);

  drawTable(doc,
    '3. DETAILED JOB REQUEST SUMMARY REPORT DATA',
    'RESPECTIVELY MAPPED REPORT COLUMNS',
    [
      { key: 'request_code',           label: 'Request ID',        width: 80 },
      { key: 'equipment_name',         label: 'Equipment Name',    width: 140 },
      { key: 'job_type',               label: 'Job Type',          width: 70 },
      { key: 'status',                 label: 'Status',            width: 90 },
      { key: 'submitted_by_name',      label: 'Submitted By',      width: 100 },
      { key: 'submitted_date',         label: 'Submitted On',      width: 70, format: fmtDate },
      { key: 'approved_by_name',       label: 'Approved By',       width: 90 },
      { key: 'rejected_by_name',       label: 'Rejected By',       width: 80 },
      { key: 'division',               label: 'Division',          width: 65 },
    ],
    payload.rows,
    payload.meta.report_title,
  );

  drawBusinessNotes(doc, [
    'Approved/Rejected info reads JR_APPROVED_* / JR_REJECTED_* (Phase 3 cols).',
    'Date filter applies to JR_CREATED_AT.',
    'Row-level scope: Normal Users see only their own JRs.',
  ], 'Acceptable when each request shows ID, status, submitter, division and lifecycle actor names.', STATUS_LEGEND);

  stampFooters(doc);
  doc.end();
}

module.exports = {
  renderCalibrationDuePdf,
  renderPendingJobsPdf,
  renderEquipmentUtilizationPdf,
  renderEngineerSummaryPdf,
  renderJobCardSummaryPdf,
  renderJobRequestSummaryPdf,
};
