// ============================================================================
// src/modules/pdf/templates/jobCardDetails.js
// ----------------------------------------------------------------------------
// PDF #2 — JOB CARD DETAILS (own design, multi-page)
//
// PHASE 11 — PDF Generation
//
// Renders the COMPLETE Job Card payload — every tab — as a single
// professional internal document. Used for archival / hand-over so a
// supervisor can read the full state of one card in one PDF without
// opening the web UI.
//
// LAYOUT
//   Page 1 starts with the shared ISRO + SAC + TIMCD header (compact),
//   then a JC-summary band (JC code, Section JobNo, Status, Priority,
//   Generated On, Generated By).
//
//   Body sections (each with a banner row + content block):
//     A. Equipment & Engineer
//     B. Accessories (parent JR + JC plug-in text)
//     C. Submitted & Received
//     D. Job Card Details (instrument received / job type / repair type / remarks)
//     E. Maintenance Details (multi-row table from jc_maintenance_details)
//     F. Equipments Used (free text)
//     G. Awaiting Information
//     H. Spares Used (multi-row table from jc_spares_used)
//     I. Contract / Warranty
//     J. Observations (free text + jc_observations_readings table)
//     K. Task Checklist (jc_task_checklist with done/total)
//     L. Documents (jc_documents — METADATA ONLY, no file bytes)
//     M. Completion
//     N. Closure
//     O. State History (job_card_status_history)
//
// PAGINATION
//   `bufferPages: true` enables a second pass to stamp "Page X of Y".
//   Each section checks the remaining vertical room and calls
//   `doc.addPage()` when there isn't enough — the header is re-drawn
//   on every fresh page via the `onPageAdded` hook below so multi-page
//   PDFs always show the official banner.
// ============================================================================

'use strict';

const PDFDocument = require('pdfkit');
const {
  PAGE_MARGIN_X,
  PAGE_MARGIN_BOTTOM,
  FOOTER_HEIGHT,
  COLORS,
  drawHeader,
  stampPageNumbers,
  fmtDate,
  fmtDateTime,
  fmtText,
} = require('./_isroHeader');


// ── Layout helpers ─────────────────────────────────────────────────────

/** Banner row at top of each section. */
function sectionBanner(doc, letter, title) {
  const x = PAGE_MARGIN_X;
  const w = doc.page.width - PAGE_MARGIN_X * 2;
  const y = doc.y;
  const h = 16;
  doc.rect(x, y, w, h).fillAndStroke(COLORS.headerBg, COLORS.border);
  doc.fillColor(COLORS.title).font('Helvetica-Bold').fontSize(9.5);
  doc.text(`${letter}. ${title}`, x + 6, y + 3, { lineBreak: false });
  doc.y = y + h + 4;
}

/**
 * Two-column grid of labelled values — FLOW-DISCIPLINED.
 *
 * Important: PDFKit auto-paginates whenever `doc.text(s, x, y)` would
 * overflow the page bottom — which silently breaks naïve absolute-Y
 * layouts (every item ends up triggering its own page break). We avoid
 * that by:
 *   1. Capping each label to one line   (`lineBreak: false`).
 *   2. Capping each value to two lines  (`lineBreak: true, height: 22,
 *      ellipsis: true`).
 *   3. Pre-calling `ensureRoomFor()` per ROW with a fixed row height so
 *      a page break is taken at a clean boundary, never mid-item.
 *
 * Row height is fixed at 30 pt — enough for label (10pt) + 2-line value
 * (10pt × 2). Long content overflows to ellipsis; the source-of-truth
 * web UI shows the full value, so this is acceptable for a print export.
 *
 * Each entry → { label, value }.
 */
function gridKV(doc, items, columns = 2) {
  const ROW_H = 30;
  const VALUE_H = 20;
  const x = PAGE_MARGIN_X;
  const w = doc.page.width - PAGE_MARGIN_X * 2;
  const colW = (w - (columns - 1) * 12) / columns;

  let col = 0;
  let rowY = doc.y;
  items.forEach((item) => {
    if (!item) return;
    if (col === 0) {
      ensureRoomFor(doc, ROW_H);
      rowY = doc.y;
    }
    const cx = x + col * (colW + 12);
    doc.font('Helvetica-Bold').fontSize(7.5).fillColor(COLORS.inkSoft);
    doc.text(item.label, cx, rowY,
             { width: colW, lineBreak: false, ellipsis: true });
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.title);
    doc.text(fmtText(item.value, '—'), cx, rowY + 10,
             { width: colW, height: VALUE_H, lineBreak: true, ellipsis: true });
    col += 1;
    if (col >= columns) {
      col = 0;
      doc.y = rowY + ROW_H;
    }
  });
  // Close out a partial trailing row so the next section starts cleanly.
  if (col > 0) {
    doc.y = rowY + ROW_H;
  }
}

/**
 * Free-text block rendered inside a soft-bordered box — FLOW-DISCIPLINED.
 *
 * We cap the block height at 60 pt (≈ 6 lines). Anything longer is
 * ellipsised — the full text remains visible in the web UI. The cap
 * keeps the print layout from sprawling and prevents PDFKit from
 * auto-paginating mid-block.
 */
function blockText(doc, label, text) {
  const BLOCK_H = 60;
  const x = PAGE_MARGIN_X;
  const w = doc.page.width - PAGE_MARGIN_X * 2;
  ensureRoomFor(doc, BLOCK_H + 14);

  doc.font('Helvetica-Bold').fontSize(7.5).fillColor(COLORS.inkSoft);
  doc.text(label, x, doc.y, { lineBreak: false });
  const y0 = doc.y + 10;
  doc.lineWidth(0.4).strokeColor(COLORS.border).rect(x, y0, w, BLOCK_H).stroke();
  doc.font('Helvetica').fontSize(9).fillColor(COLORS.title);
  doc.text(fmtText(text, '—'), x + 4, y0 + 3,
           { width: w - 8, height: BLOCK_H - 6, lineBreak: true, ellipsis: true });
  doc.y = y0 + BLOCK_H + 6;
}

/** Page-break-aware spacer — adds a fresh page when the next block won't fit. */
function ensureRoomFor(doc, neededHeight) {
  if (doc.y + neededHeight > doc.page.height - PAGE_MARGIN_BOTTOM - FOOTER_HEIGHT) {
    doc.addPage();
  }
}

/**
 * Render a wide table with header + rows.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} title
 * @param {Array<{header, key, width, align?, format?}>} columns
 * @param {Array<object>} rows
 */
function drawTable(doc, title, columns, rows) {
  const x = PAGE_MARGIN_X;
  const tableW = doc.page.width - PAGE_MARGIN_X * 2;
  const totalRaw = columns.reduce((a, c) => a + c.width, 0);
  const widths = columns.map((c) => (c.width / totalRaw) * tableW);
  const HEADER_H = 18;
  const PAD = 4;

  if (title) {
    doc.font('Helvetica-Bold').fontSize(8.5).fillColor(COLORS.title);
    doc.text(title, x, doc.y);
    doc.y += 2;
  }
  // Header
  ensureRoomFor(doc, HEADER_H + 18);
  const hy = doc.y;
  doc.rect(x, hy, tableW, HEADER_H).fillAndStroke(COLORS.headerBg, COLORS.border);
  doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.title);
  let cx = x;
  columns.forEach((c, i) => {
    doc.text(c.header, cx + PAD, hy + 4, { width: widths[i] - 2 * PAD, align: c.align || 'left', lineBreak: false });
    cx += widths[i];
  });
  doc.y = hy + HEADER_H;

  if (!rows || rows.length === 0) {
    doc.font('Helvetica-Oblique').fontSize(8).fillColor(COLORS.inkSoft);
    doc.text('No data recorded.', x + 4, doc.y + 3);
    doc.y += 16;
    return;
  }

  doc.font('Helvetica').fontSize(8).fillColor(COLORS.title);
  rows.forEach((row) => {
    // Estimate row height — worst-case wrapping at ~50 chars per cell width
    let needed = 18;
    columns.forEach((c, i) => {
      const v = c.format ? c.format(row[c.key], row) : (row[c.key] ?? '');
      const chars = String(v).length;
      const cpl = Math.max(8, Math.floor((widths[i] - 2 * PAD) / 4.5));
      const lines = Math.min(4, Math.max(1, Math.ceil(chars / cpl)));
      const h = 6 + lines * 10;
      if (h > needed) needed = h;
    });
    ensureRoomFor(doc, needed);
    const ry = doc.y;
    doc.lineWidth(0.3).strokeColor(COLORS.border).rect(x, ry, tableW, needed).stroke();
    cx = x;
    columns.forEach((c, i) => {
      const v = c.format ? c.format(row[c.key], row) : (row[c.key] ?? '');
      doc.text(String(v ?? ''), cx + PAD, ry + 3, {
        width: widths[i] - 2 * PAD,
        align: c.align || 'left',
        height: needed - 6,
        ellipsis: true,
      });
      cx += widths[i];
    });
    doc.y = ry + needed;
  });
  doc.y += 4;
}


/** Build "JC-YYYY-NNNN" the same way Phase 6 D-4 does. */
function jcCode(main) {
  const year = main.jc_recd_date ? new Date(main.jc_recd_date).getUTCFullYear() : '----';
  const num  = String(main.jc_no || '').padStart(4, '0');
  return `JC-${year}-${num}`;
}

function jrCode(main) {
  if (!main.parent_jr_no) return '—';
  const year = main.jr_request_date ? new Date(main.jr_request_date).getUTCFullYear() : '----';
  return `JR-${year}-${String(main.parent_jr_no).padStart(4, '0')}`;
}


// ── MAIN RENDERER ──────────────────────────────────────────────────────

function renderJobCardDetails(payload, stream, meta = {}) {
  const doc = new PDFDocument({
    size: 'A4',
    layout: 'portrait',
    margin: PAGE_MARGIN_X,
    bufferPages: true,
    autoFirstPage: true,
  });
  doc.pipe(stream);

  // ── Header on page 1 only ──────────────────────────────────────────
  // We intentionally do NOT bind drawHeader to PDFKit's `pageAdded` event.
  // Doing so creates re-entrant rendering when text() auto-paginates,
  // which produces near-empty pages. Subsequent pages get the docId +
  // "Page X of Y" footer (stamped in a second pass at the end), which
  // is enough provenance for a print export.
  drawHeader(doc, {
    title: 'JOB CARD — DETAILS REPORT',
    subtitle: 'CMCMIS · Internal Document',
    compact: true,
  });

  // ── Summary band ───────────────────────────────────────────────────
  const code = jcCode(payload);
  const summary = [
    { label: 'Job Card Code',  value: code },
    { label: 'Section Job No', value: payload.section_job_no },
    { label: 'Parent JR',      value: jrCode(payload) },
    { label: 'Status',         value: payload.status },
    { label: 'Priority',       value: payload.jr_priority_db || '—' },
    { label: 'Workflow Type',  value: payload.workflow_type },
    { label: 'Generated On',   value: fmtDateTime(new Date()) },
    { label: 'Generated By',   value: meta.generated_by
        ? `${meta.generated_by.name || meta.generated_by.employee_id || '—'} (${meta.generated_by.role || '—'})`
        : '—' },
  ];
  gridKV(doc, summary, 4);

  // ── A. Equipment & Engineer ────────────────────────────────────────
  sectionBanner(doc, 'A', 'Equipment & Assigned Engineer');
  gridKV(doc, [
    { label: 'Equipment Name', value: payload.equipment_name },
    { label: 'Make',           value: payload.equipment_make },
    { label: 'Model No.',      value: payload.equipment_model_no || payload.equipment_mfg_model_name },
    { label: 'Serial No.',     value: payload.equipment_serial_no },
    { label: 'Division',       value: payload.division_code
        ? `${payload.division_code} — ${payload.division_name || ''}`.trim()
        : payload.division_name },
    { label: 'Assigned Engineer',
      value: payload.assigned_engineer_employee_id
        ? `${payload.assigned_engineer_name || ''} (${payload.assigned_engineer_employee_id})`
        : '—' },
  ], 2);

  // ── B. Accessories ─────────────────────────────────────────────────
  sectionBanner(doc, 'B', 'Accessories');
  const accRows = (payload.children?.parent_accessories || []).map((a, i) => ({
    sr_no: i + 1, type: a.type, name: a.name, serial_no: a.serial_no,
  }));
  drawTable(doc, null, [
    { header: '#',         key: 'sr_no',     width: 30,  align: 'right' },
    { header: 'Item Type', key: 'type',      width: 100 },
    { header: 'Item Name', key: 'name',      width: 220 },
    { header: 'Serial No.',key: 'serial_no', width: 120 },
  ], accRows);
  if (payload.plug_in_accessories) {
    blockText(doc, 'Plug-in Accessories (free text)', payload.plug_in_accessories);
  }

  // ── C. Submitted & Received ────────────────────────────────────────
  sectionBanner(doc, 'C', 'Submitted & Received');
  gridKV(doc, [
    { label: 'Equipment Submitted Date', value: fmtDate(payload.equipment_submitted_date) },
    { label: 'Submitted By',             value: payload.submitted_by },
    { label: 'Equipment Received Date',  value: fmtDate(payload.equipment_received_date_actual) },
    { label: 'Received By',              value: payload.received_by },
    { label: 'JC Received Date',         value: fmtDate(payload.jc_recd_date) },
    { label: 'Instrument Received Date', value: fmtDate(payload.instrument_received_date || payload.inst_recd_date) },
  ], 2);

  // ── D. Job Card Details ────────────────────────────────────────────
  sectionBanner(doc, 'D', 'Job Card Details');
  gridKV(doc, [
    { label: 'Job Type',             value: payload.phase9_job_type },
    { label: 'Repair Type',          value: payload.repair_type },
    { label: 'Planned Start',        value: fmtDate(payload.planned_start_date) },
    { label: 'Planned Completion',   value: fmtDate(payload.job_complete_planned_date || payload.planned_completed_date) },
    { label: 'Job Started On',       value: fmtDate(payload.job_start_date) },
    { label: 'Job Ended On',         value: fmtDate(payload.job_end_date) },
  ], 2);
  if (payload.job_request_remarks) blockText(doc, 'Job Request Remarks', payload.job_request_remarks);
  if (payload.complaint_description) blockText(doc, 'Complaint / Symptoms', payload.complaint_description);

  // ── E. Maintenance Details (multi-row) ─────────────────────────────
  sectionBanner(doc, 'E', `Maintenance Details (${(payload.children?.maintenance || []).length} rows)`);
  drawTable(doc, null, [
    { header: '#',                     key: 'sr_no',              width: 30,  align: 'right' },
    { header: 'Defect / Symptom',      key: 'defect_description', width: 160 },
    { header: 'Observation',           key: 'observation',        width: 160 },
    { header: 'Action Taken',          key: 'action_taken',       width: 160 },
    { header: 'Remarks',               key: 'remarks',            width: 120 },
  ], payload.children?.maintenance || []);

  // ── F. Equipments Used ─────────────────────────────────────────────
  sectionBanner(doc, 'F', 'Equipments Used');
  blockText(doc, 'Equipments Used', payload.equipments_used);

  // ── G. Awaiting Information ────────────────────────────────────────
  sectionBanner(doc, 'G', 'Awaiting Information');
  gridKV(doc, [
    { label: 'Awaiting For',       value: payload.awaiting_for },
    { label: 'Awaiting Status',    value: payload.awaiting_status },
    { label: 'Supplier Name',      value: payload.supplier_name },
    { label: 'Attended By',        value: payload.attended_by },
    { label: 'Awaiting From',      value: fmtDate(payload.awaiting_from_date) },
    { label: 'Awaiting Cleared',   value: fmtDate(payload.awaiting_clear_date) },
    { label: 'Indent No.',         value: payload.indent_no },
    { label: 'Indent Date',        value: fmtDate(payload.indent_date) },
    { label: 'MIRV No.',           value: payload.mirv_no },
    { label: 'MIRV Date',          value: fmtDate(payload.mirv_date) },
    { label: 'PO No.',             value: payload.po_no },
    { label: 'PO Date',            value: fmtDate(payload.po_date) },
    { label: 'Procurement Cost',   value: payload.procurement_cost },
  ], 2);

  // ── H. Spares Used (multi-row) ─────────────────────────────────────
  sectionBanner(doc, 'H', `Spares Used (${(payload.children?.spares || []).length} rows)`);
  drawTable(doc, null, [
    { header: '#',           key: 'sr_no',            width: 25,  align: 'right' },
    { header: 'Spare Type',  key: 'spare_type',       width: 90 },
    { header: 'Source',      key: 'source',           width: 70 },
    { header: 'Part No.',    key: 'part_no',          width: 90 },
    { header: 'Description', key: 'part_description', width: 180 },
    { header: 'Qty',         key: 'quantity',         width: 35,  align: 'right' },
    { header: 'Cost',        key: 'cost',             width: 60,  align: 'right' },
  ], payload.children?.spares || []);

  // ── I. Contract / Warranty ─────────────────────────────────────────
  sectionBanner(doc, 'I', 'Contract / Warranty');
  gridKV(doc, [
    { label: 'Vendor / Supplier',          value: payload.vendor_supplier_name },
    { label: 'Intimation Sent On',         value: fmtDate(payload.intimation_sent_on) },
    { label: 'Sent to Vendor Date',        value: fmtDate(payload.sent_to_vendor_date) },
    { label: 'Received from Vendor Date',  value: fmtDate(payload.received_from_vendor_date) },
    { label: 'Gate Pass No.',              value: payload.gate_pass_no },
    { label: 'Gate Pass Issued',           value: fmtDate(payload.gate_pass_issued_date) },
    { label: 'Cost of Component',          value: payload.cost_of_component },
    { label: 'Labour Charges',             value: payload.labour_charges },
    { label: 'Invoice No.',                value: payload.invoice_no },
    { label: 'Invoice Received On',        value: fmtDate(payload.invoice_recd_on) },
  ], 2);

  // ── J. Observations ────────────────────────────────────────────────
  sectionBanner(doc, 'J', 'Observations');
  blockText(doc, 'Observations Text', payload.observations_text);
  gridKV(doc, [
    { label: 'Job Status Display', value: payload.job_status_display },
  ], 1);
  drawTable(doc, 'Readings', [
    { header: 'Parameter',    key: 'parameter',     width: 130 },
    { header: 'Value',        key: 'value',         width: 80 },
    { header: 'Unit',         key: 'unit',          width: 50 },
    { header: 'Type',         key: 'reading_type',  width: 80 },
    { header: 'Recorded At',  key: 'recorded_at',   width: 110, format: fmtDateTime },
    { header: 'Notes',        key: 'notes',         width: 110 },
  ], payload.children?.observations || []);

  // ── K. Task Checklist ──────────────────────────────────────────────
  const tasks = payload.children?.tasks || [];
  const doneCount = tasks.filter((t) => t.is_completed === 1 || t.is_completed === true).length;
  sectionBanner(doc, 'K', `Task Checklist (${doneCount}/${tasks.length} done)`);
  drawTable(doc, null, [
    { header: 'Task',          key: 'task_text',    width: 320 },
    { header: 'Custom?',       key: 'is_custom',    width: 60, format: (v) => v ? 'Yes' : 'No' },
    { header: 'Done?',         key: 'is_completed', width: 60, format: (v) => v ? '✓ Done' : '— Open' },
    { header: 'Completed At',  key: 'completed_at', width: 120, format: fmtDateTime },
  ], tasks);

  // ── L. Documents (metadata only) ───────────────────────────────────
  sectionBanner(doc, 'L', `Documents (${(payload.children?.documents || []).length} files — metadata only)`);
  drawTable(doc, null, [
    { header: 'Filename',  key: 'filename',     width: 200 },
    { header: 'Type',      key: 'doc_type',     width: 110 },
    { header: 'Mime',      key: 'mimetype',     width: 110 },
    { header: 'Size (B)',  key: 'size_bytes',   width: 70, align: 'right',
      format: (v) => (v == null ? '—' : Number(v).toLocaleString()) },
    { header: 'Uploaded',  key: 'uploaded_at',  width: 130, format: fmtDateTime },
  ], payload.children?.documents || []);

  // ── M. Completion ──────────────────────────────────────────────────
  sectionBanner(doc, 'M', 'Completion');
  gridKV(doc, [
    { label: 'Actual Completion Date',  value: fmtDate(payload.actual_completion_date) },
    { label: 'Total Hours Spent',       value: payload.total_hours_spent },
    { label: 'Marked Complete By',      value: payload.marked_complete_by_employee_id
        ? `${payload.marked_complete_by_name || ''} (${payload.marked_complete_by_employee_id})`
        : '—' },
    { label: 'Marked Complete At',      value: fmtDateTime(payload.marked_complete_at) },
  ], 2);
  blockText(doc, 'Completion Summary', payload.completion_summary);

  // ── N. Closure ─────────────────────────────────────────────────────
  sectionBanner(doc, 'N', 'Closure');
  gridKV(doc, [
    { label: 'Reviewed By',                       value: payload.reviewed_by },
    { label: 'Review Date',                       value: fmtDate(payload.review_date) },
    { label: 'Equipment Received By Customer',    value: payload.equipment_received_by_customer },
    { label: 'Customer Received Date',            value: fmtDate(payload.customer_received_date) },
    { label: 'Customer Acknowledged',             value: payload.customer_acknowledged ? 'Yes' : 'No' },
    { label: 'Verified-Closed By',                value: payload.verified_closed_by_employee_id
        ? `${payload.verified_closed_by_name || ''} (${payload.verified_closed_by_employee_id})`
        : '—' },
    { label: 'Verified-Closed At',                value: fmtDateTime(payload.verified_closed_at) },
    { label: 'Reopen Count',                      value: payload.reopen_count ?? 0 },
  ], 2);
  blockText(doc, 'Review Comments',     payload.review_comments);
  blockText(doc, 'Final Closure Notes', payload.final_closure_notes);

  // ── O. State History ───────────────────────────────────────────────
  sectionBanner(doc, 'O', `State Transition History (${(payload.children?.history || []).length} entries)`);
  drawTable(doc, null, [
    { header: 'From',          key: 'from_status',     width: 100 },
    { header: 'To',            key: 'to_status',       width: 100 },
    { header: 'When',          key: 'transitioned_at', width: 130, format: fmtDateTime },
    { header: 'By',            key: 'transitioned_by', width: 100 },
    { header: 'Reason',        key: 'reason',          width: 150 },
  ], payload.children?.history || []);

  // ── Stamp page numbers + footer on every page ──────────────────────
  stampPageNumbers(doc, { docId: code });
  doc.end();
}


module.exports = {
  renderJobCardDetails,
};
